// Shared web-push helpers: the VAPID application server + the single encrypted
// send call, plus small copy utilities (interpolate + clip to iOS limits).
//
// ⚠ SPIKE TARGET: the @negrel/webpush call below is the one piece that must be
// validated live against a real *.push.apple.com endpoint before the rest of
// the system is trusted (Phase 0 of docs/push-notifications-spec.md). It is
// isolated here so that if the library's surface differs from this, only
// sendPush() changes.
//
// Required Supabase secrets:
//   VAPID_KEYS    — JSON of the VAPID key pair as JWK: { publicKey, privateKey }.
//                   Generated by scripts/generate-vapid-keys.mjs alongside the
//                   base64url public key that the frontend's VITE_VAPID_PUBLIC_KEY
//                   uses — the two MUST come from the same key pair.
//   VAPID_SUBJECT — contact mailto: (e.g. mailto:rob@plasmadesign.co.uk).

import * as webpush from 'jsr:@negrel/webpush@^0.5.0'

export interface PushTarget {
  endpoint: string
  p256dh: string
  auth: string
}

export interface PushPayload {
  title: string
  body: string
  url: string
  tag?: string
}

export type SendOutcome =
  | { ok: true }
  | { ok: false; status: number | null; error: string }

let appServerPromise: Promise<webpush.ApplicationServer> | null = null

async function getAppServer(): Promise<webpush.ApplicationServer> {
  if (!appServerPromise) {
    const keysJson = Deno.env.get('VAPID_KEYS')
    const subject = Deno.env.get('VAPID_SUBJECT')?.trim() || 'mailto:rob@plasmadesign.co.uk'
    if (!keysJson) throw new Error('VAPID_KEYS not configured')
    appServerPromise = (async () => {
      const vapidKeys = await webpush.importVapidKeys(JSON.parse(keysJson), { extractable: false })
      return await webpush.ApplicationServer.new({
        contactInformation: subject,
        vapidKeys,
      })
    })()
  }
  return appServerPromise
}

/**
 * Encrypt + deliver one notification to one device subscription. Returns a
 * structured outcome (never throws) so the caller can prune dead subscriptions
 * on 404/410 and log the rest.
 */
export async function sendPush(target: PushTarget, payload: PushPayload): Promise<SendOutcome> {
  try {
    const appServer = await getAppServer()
    const subscriber = appServer.subscribe({
      endpoint: target.endpoint,
      keys: { p256dh: target.p256dh, auth: target.auth },
    })
    await subscriber.pushTextMessage(JSON.stringify(payload), {})
    return { ok: true }
  } catch (err) {
    // @negrel/webpush throws PushMessageError carrying the upstream Response on
    // a non-2xx from the push service; 404/410 there means the subscription is
    // gone and the caller should delete it.
    const status =
      (err as { response?: { status?: number } })?.response?.status ?? null
    return { ok: false, status, error: err instanceof Error ? err.message : String(err) }
  }
}

/** Replace {key} placeholders from vars; unknown/missing keys become ''. */
export function interpolate(template: string, vars: Record<string, string | null | undefined>): string {
  return template.replace(/\{(\w+)\}/g, (_m, key: string) => {
    const v = vars[key]
    return v == null ? '' : String(v)
  })
}

/** Clip to a max length with an ellipsis — keeps the lock-screen copy within
 *  the iOS title/body limits and the payload small. */
export function clip(s: string, max: number): string {
  const trimmed = s.trim()
  if (trimmed.length <= max) return trimmed
  return trimmed.slice(0, Math.max(0, max - 1)).trimEnd() + '…'
}
