-- Migration 000193: allow SVG uploads to the proof-images bucket.
--
-- Migration 000192 added hosted-vCard QR codes. The proof viewer
-- generates those QRs as SVGs — vector, so the designer can place a
-- crisp QR in the print artwork, and tiny on disk. The version-save
-- flow uploads the generated SVG to the proof-images storage bucket.
--
-- That bucket has been JPEG-only since migration 000032, so the
-- upload was rejected with "mime type image/svg+xml is not
-- supported". This adds image/svg+xml to the allowed list.
--
-- image/jpeg is retained: it is still the format for uploaded
-- artwork images and for customer-supplied QR images (the existing
-- upload-and-decode path).
--
-- Safe to allow: every proof image, QR SVGs included, is rendered
-- through an <img> tag (the customer-page QrCodePanel and the
-- designer-side QrCodeUploadSection). Browsers do not execute
-- scripts in an SVG loaded via <img>, and the hosted-vCard QR SVGs
-- are machine-generated by the qrcode library with no script
-- content regardless.

begin;

update storage.buckets
  set allowed_mime_types = array['image/jpeg', 'image/svg+xml']
  where id = 'proof-images';

commit;
