-- Private storage bucket for proof images.
-- public = false means direct URL access is always blocked.
-- Access is only possible via signed URLs generated by the app.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'proof-images',
  'proof-images',
  false,
  10485760,                        -- 10 MB in bytes
  array['image/jpeg', 'image/png'] -- JPEG and PNG only
);

-- Authenticated designers can upload and manage images.
create policy "proof-images: authenticated upload"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'proof-images');

create policy "proof-images: authenticated select"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'proof-images');

create policy "proof-images: authenticated update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'proof-images');

create policy "proof-images: authenticated delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'proof-images');

-- Anonymous users can generate signed URLs for images they know the path to.
-- The bucket remains private (no direct access); this only allows the signed
-- URL generation call that the customer proof page makes on load.
create policy "proof-images: anon signed url"
  on storage.objects for select
  to anon
  using (bucket_id = 'proof-images');
